[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "layer-notebook-dash"
version = "0.1.0"
description = "Interactive code editor (IDE) for Kaggle and Jupyter notebooks with Layer.Dash"
readme = "README.md"
authors = [
    { name = "Layer Dev Team" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: IPython",
    "Framework :: Jupyter",
]
dependencies = [
    "IPython>=7.0.0",
    "ipykernel>=6.0.0",
    "ipywidgets>=7.6.0",
]

[project.urls]
Homepage = "https://github.com/layer/layer-notebook-dash"
